"""
Django settings for _04_qna project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w=0hdmut4)kg(gh@=g9esvcn@a=u0!82dd+@-^+w&^9dlra9q6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost').split(',')


# Application definition

# 1. app 등록
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'qna',
    'uauth'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = '_04_qna.urls'

# 2. template 등록
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = '_04_qna.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# 3. database 등록
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'qnadb',
        'USER' : 'django',
        'PASSWORD' : 'django', 
        'HOST' : '127.0.0.1',
        'PORT' : '3306',
        # 이모지 처리를 위한 인코딩 utf8mb4를 사용한 database(schema)인 경우 선언
        'OPTIONS': {
            'charset': 'utf8mb4',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # username/email등과 유사한 비밀번호 금지
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        # 최소길이 설정 (기본값: 8)
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 4,
        }
    },
    # {
    #     # 일반적인 비밀번호 금지
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     # 숫자만으로 구성된 비밀번호 금지
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 4. 언어 및 지역 설정
LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# 5. static 경로 설정
STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# MEDIA_URL: 브라우저가 파일에 접근할 때 URL 접두사
# MEDIA_ROOT: 서버 컴퓨터 상에 실제 저장 디렉토리 경로
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 6. query 로그 설정(개발 시에만)
# ORM 쿼리 로그 출력 (형식지정)

import sqlparse

class SQLFormatter:
    def format(self, record):
        if record.sql:
            formatted_sql = sqlparse.format(record.sql, reindent=True, keyword_case='upper')
            execution_time = getattr(record, 'duration', 0.0) # duration 속성이 없을 경우 기본값 0.0을 사용
            return f'{formatted_sql}\n[Execution Time: {execution_time:.3f} ms]'
        return record.getMessage()

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'custom_sql',
        },
    },
    'formatters': {
        'custom_sql': {
            '()': SQLFormatter,
        },
    },
    'loggers': {
        'django.db.backends': {
            'level': 'DEBUG',
            'handlers': ['console'],
        },
    },
}

# 7. 로그인 성공 후 리다이렉트 URL (기본값: /accounts/profile)
LOGIN_REDIRECT_URL = '/qna/'
