# Generated by Django 6.0.5 on 2026-05-13 03:31

import uauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=uauth.models.profile_upload_path),
        ),
    ]
